application: html5-diplomado
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|pdf|JPG|js|wma|mp3))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico|pdf|JPG|js|wma|mp3))
  
- url: /stylesheets
  static_dir: stylesheets   
  
- url: /.*
  script: helloworld.py
